### PR TITLE
Issue 3

### PR DESCRIPTION
**Pull request by soupdiver**
I've made it more readable (in my opinion) and fixed Issue #3
also fixed a small naming issue
@pjan

### CODE REVIEW

**Comment by pjan** [comment]
@soupdiver The tests succeed, but that's only because it's omitting most of the tasks as no data is provided. `default` was introduced post `1.5.0`, so [this line](https://github.com/ANXS/generic-users/blob/master/.travis.yml#L8) will need to be updated.

Adding @otakup0pe to the conversation as well, since he has been focussing on tests. Just so he is aware.

If you change that line, than this is excellent. :ok_woman:

**Comment by soupdiver** [comment]
ok I've updated the travis line and also the README to mention that Ansible 1.8 is required :)

**Comment by pjan** [comment]
:+1:

As you're as much of a maintainer as myself, feel free to merge it, as well as publish a version and update galaxy. Let me know if you run into an issue

**Comment by soupdiver** [comment]
ok cool. Just wanted to get the ok :)

**Pull request merged**
