### PR TITLE
storing the public keys in the files folder

### PR DESCRIPTION
**Pull request by danvaida**
tidies up the defaults file a little bit

### CODE REVIEW

**Comment by farridav** [comment]
How do people currently use this role? if the files are stored in `files` it is not easily accessible for the user right? plus it would break their existing plays that use absolute paths.

If i wanted to use this as part of my play, i would install it via ansbile galaxy, so the `files` folder would be in `./myproject/.installed_roles/generic-users/files` which is an obscure place for me to track my keys, and one that i keep in my gitignore too.. if ive misunderstood please let me know :smile:

**Comment by danvaida** [comment]
What do you mean by "it is not easily accessible for the user"? Also, what plays are you talking about? Can you be more specific/show an example?

On your other note, the path from where to pick up the key(s) can be set as a variable as well. I wouldn't look at the 'files' folder as something mandatory/show stopper.

It's fine if the PR won't make it through, I just don't like to copy-paste public keys around. I'd rather put them all in one place and parse them while keeping the vars file as clean as possible.

**Comment by farridav** [comment]
Hi @danvaida, consider a play like this:
```
---

- name: test
  hosts: all
  vars:
    genericusers_users:
      - name: "foo"
        ...
        ssh_keys:
          - "id_rsa.pub"
  roles:
    - role: ANXS.generic-users
```

When i run this i get `could not locate file in lookup: ../files/id_rsa.pub` because of the lookup using the roles `files` directory, i would suggest either keeping an absolute path, or better still use the readme to advise people to use a lookup in their vars, e.g:-   

---

- name: test
    ...
    genericusers_users:
      - name: "foo"
        groups: ["dbadmins", "mailadmins"]
        ssh_keys:           # Keys to add to authorized_keys. Store them in the files directory.
          - "{{ lookup('file', '/any/path/you/like/outside/or/inside/the/role/id_rsa.pub' }}"
          - "{{ lookup('file', '/home/myuser/id_rsa.pub' }}"
        ...
  roles:
    - role: ANXS.generic-users
```

I hope ive explained that properly :smile: let me know if ive overlooked something

**Comment by danvaida** [comment]
That's a valid point. However it may be, these are
implementation/documentation details all derived from one starting point:
keep the public keys out of the vars file. I guess it might be a good
compromise to keep the lookup plugin invocation flexible.

I for one, like to keep my expected resources together with the role that
expects them. When multiple roles need the same thing, then you can
re-think this approach.

Hope this makes sense.

**Comment by otakup0pe** [comment]
I like this concept but would also want it to be an absolute path.

**Comment by otakup0pe** [comment]
I ended up taking a different approach to this problem... It leaves the core mechanic alone but allows you to populate the variables using external files https://github.com/ANXS/generic-users/pull/16

**Pull request closed without merging**
